/*
 * This file is generated by jOOQ.
 */
package com.assessment.assessment.database.tables.records;


import com.assessment.assessment.database.tables.IqDoctor;

import java.time.LocalDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class IqDoctorRecord extends UpdatableRecordImpl<IqDoctorRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>iq_doctor.id</code>.
     */
    public IqDoctorRecord setId(Long value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>iq_doctor.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>iq_doctor.client_id</code>.
     */
    public IqDoctorRecord setClientId(Integer value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>iq_doctor.client_id</code>.
     */
    public Integer getClientId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>iq_doctor.name</code>.
     */
    public IqDoctorRecord setName(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>iq_doctor.name</code>.
     */
    public String getName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>iq_doctor.specialization_id</code>.
     */
    public IqDoctorRecord setSpecializationId(Long value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>iq_doctor.specialization_id</code>.
     */
    public Long getSpecializationId() {
        return (Long) get(3);
    }

    /**
     * Setter for <code>iq_doctor.is_deleted</code>.
     */
    public IqDoctorRecord setIsDeleted(Boolean value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>iq_doctor.is_deleted</code>.
     */
    public Boolean getIsDeleted() {
        return (Boolean) get(4);
    }

    /**
     * Setter for <code>iq_doctor.created_on</code>.
     */
    public IqDoctorRecord setCreatedOn(LocalDateTime value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>iq_doctor.created_on</code>.
     */
    public LocalDateTime getCreatedOn() {
        return (LocalDateTime) get(5);
    }

    /**
     * Setter for <code>iq_doctor.created_by</code>.
     */
    public IqDoctorRecord setCreatedBy(Long value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>iq_doctor.created_by</code>.
     */
    public Long getCreatedBy() {
        return (Long) get(6);
    }

    /**
     * Setter for <code>iq_doctor.updated_on</code>.
     */
    public IqDoctorRecord setUpdatedOn(LocalDateTime value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for <code>iq_doctor.updated_on</code>.
     */
    public LocalDateTime getUpdatedOn() {
        return (LocalDateTime) get(7);
    }

    /**
     * Setter for <code>iq_doctor.updated_by</code>.
     */
    public IqDoctorRecord setUpdatedBy(Long value) {
        set(8, value);
        return this;
    }

    /**
     * Getter for <code>iq_doctor.updated_by</code>.
     */
    public Long getUpdatedBy() {
        return (Long) get(8);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached IqDoctorRecord
     */
    public IqDoctorRecord() {
        super(IqDoctor.IQ_DOCTOR);
    }

    /**
     * Create a detached, initialised IqDoctorRecord
     */
    public IqDoctorRecord(Long id, Integer clientId, String name, Long specializationId, Boolean isDeleted, LocalDateTime createdOn, Long createdBy, LocalDateTime updatedOn, Long updatedBy) {
        super(IqDoctor.IQ_DOCTOR);

        setId(id);
        setClientId(clientId);
        setName(name);
        setSpecializationId(specializationId);
        setIsDeleted(isDeleted);
        setCreatedOn(createdOn);
        setCreatedBy(createdBy);
        setUpdatedOn(updatedOn);
        setUpdatedBy(updatedBy);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised IqDoctorRecord
     */
    public IqDoctorRecord(com.assessment.assessment.database.tables.pojos.IqDoctor value) {
        super(IqDoctor.IQ_DOCTOR);

        if (value != null) {
            setId(value.getId());
            setClientId(value.getClientId());
            setName(value.getName());
            setSpecializationId(value.getSpecializationId());
            setIsDeleted(value.getIsDeleted());
            setCreatedOn(value.getCreatedOn());
            setCreatedBy(value.getCreatedBy());
            setUpdatedOn(value.getUpdatedOn());
            setUpdatedBy(value.getUpdatedBy());
            resetChangedOnNotNull();
        }
    }
}
