/*
 * This file is generated by jOOQ.
 */
package com.assessment.assessment.database.tables.records;


import com.assessment.assessment.database.tables.IqPatientDept;

import java.time.LocalDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class IqPatientDeptRecord extends UpdatableRecordImpl<IqPatientDeptRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>iq_patient_dept.id</code>.
     */
    public IqPatientDeptRecord setId(Long value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>iq_patient_dept.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>iq_patient_dept.name</code>.
     */
    public IqPatientDeptRecord setName(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>iq_patient_dept.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>iq_patient_dept.dob</code>.
     */
    public IqPatientDeptRecord setDob(LocalDateTime value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>iq_patient_dept.dob</code>.
     */
    public LocalDateTime getDob() {
        return (LocalDateTime) get(2);
    }

    /**
     * Setter for <code>iq_patient_dept.address</code>.
     */
    public IqPatientDeptRecord setAddress(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>iq_patient_dept.address</code>.
     */
    public String getAddress() {
        return (String) get(3);
    }

    /**
     * Setter for <code>iq_patient_dept.doctor_id</code>.
     */
    public IqPatientDeptRecord setDoctorId(Long value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>iq_patient_dept.doctor_id</code>.
     */
    public Long getDoctorId() {
        return (Long) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached IqPatientDeptRecord
     */
    public IqPatientDeptRecord() {
        super(IqPatientDept.IQ_PATIENT_DEPT);
    }

    /**
     * Create a detached, initialised IqPatientDeptRecord
     */
    public IqPatientDeptRecord(Long id, String name, LocalDateTime dob, String address, Long doctorId) {
        super(IqPatientDept.IQ_PATIENT_DEPT);

        setId(id);
        setName(name);
        setDob(dob);
        setAddress(address);
        setDoctorId(doctorId);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised IqPatientDeptRecord
     */
    public IqPatientDeptRecord(com.assessment.assessment.database.tables.pojos.IqPatientDept value) {
        super(IqPatientDept.IQ_PATIENT_DEPT);

        if (value != null) {
            setId(value.getId());
            setName(value.getName());
            setDob(value.getDob());
            setAddress(value.getAddress());
            setDoctorId(value.getDoctorId());
            resetChangedOnNotNull();
        }
    }
}
