/*
 * This file is generated by jOOQ.
 */
package com.assessment.assessment.database.tables.records;


import com.assessment.assessment.database.tables.IqSpecializationMaster;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class IqSpecializationMasterRecord extends UpdatableRecordImpl<IqSpecializationMasterRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>iq_specialization_master.id</code>.
     */
    public IqSpecializationMasterRecord setId(Long value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>iq_specialization_master.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>iq_specialization_master.title</code>.
     */
    public IqSpecializationMasterRecord setTitle(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>iq_specialization_master.title</code>.
     */
    public String getTitle() {
        return (String) get(1);
    }

    /**
     * Setter for <code>iq_specialization_master.des</code>.
     */
    public IqSpecializationMasterRecord setDes(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>iq_specialization_master.des</code>.
     */
    public String getDes() {
        return (String) get(2);
    }

    /**
     * Setter for <code>iq_specialization_master.client_id</code>.
     */
    public IqSpecializationMasterRecord setClientId(Integer value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>iq_specialization_master.client_id</code>.
     */
    public Integer getClientId() {
        return (Integer) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached IqSpecializationMasterRecord
     */
    public IqSpecializationMasterRecord() {
        super(IqSpecializationMaster.IQ_SPECIALIZATION_MASTER);
    }

    /**
     * Create a detached, initialised IqSpecializationMasterRecord
     */
    public IqSpecializationMasterRecord(Long id, String title, String des, Integer clientId) {
        super(IqSpecializationMaster.IQ_SPECIALIZATION_MASTER);

        setId(id);
        setTitle(title);
        setDes(des);
        setClientId(clientId);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised IqSpecializationMasterRecord
     */
    public IqSpecializationMasterRecord(com.assessment.assessment.database.tables.pojos.IqSpecializationMaster value) {
        super(IqSpecializationMaster.IQ_SPECIALIZATION_MASTER);

        if (value != null) {
            setId(value.getId());
            setTitle(value.getTitle());
            setDes(value.getDes());
            setClientId(value.getClientId());
            resetChangedOnNotNull();
        }
    }
}
