/*
 * This file is generated by jOOQ.
 */
package com.assessment.assessment.database.tables.records;


import com.assessment.assessment.database.tables.IqSpecializationDoctorMapping;

import java.time.LocalDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class IqSpecializationDoctorMappingRecord extends UpdatableRecordImpl<IqSpecializationDoctorMappingRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>iq_specialization_doctor_mapping.id</code>.
     */
    public IqSpecializationDoctorMappingRecord setId(Long value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>iq_specialization_doctor_mapping.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>iq_specialization_doctor_mapping.doctor_id</code>.
     */
    public IqSpecializationDoctorMappingRecord setDoctorId(Long value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>iq_specialization_doctor_mapping.doctor_id</code>.
     */
    public Long getDoctorId() {
        return (Long) get(1);
    }

    /**
     * Setter for
     * <code>iq_specialization_doctor_mapping.specialization_id</code>.
     */
    public IqSpecializationDoctorMappingRecord setSpecializationId(Long value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for
     * <code>iq_specialization_doctor_mapping.specialization_id</code>.
     */
    public Long getSpecializationId() {
        return (Long) get(2);
    }

    /**
     * Setter for
     * <code>iq_specialization_doctor_mapping.iq_specializationcol</code>.
     */
    public IqSpecializationDoctorMappingRecord setIqSpecializationcol(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for
     * <code>iq_specialization_doctor_mapping.iq_specializationcol</code>.
     */
    public String getIqSpecializationcol() {
        return (String) get(3);
    }

    /**
     * Setter for <code>iq_specialization_doctor_mapping.created_by</code>.
     */
    public IqSpecializationDoctorMappingRecord setCreatedBy(Long value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>iq_specialization_doctor_mapping.created_by</code>.
     */
    public Long getCreatedBy() {
        return (Long) get(4);
    }

    /**
     * Setter for <code>iq_specialization_doctor_mapping.created_on</code>.
     */
    public IqSpecializationDoctorMappingRecord setCreatedOn(LocalDateTime value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>iq_specialization_doctor_mapping.created_on</code>.
     */
    public LocalDateTime getCreatedOn() {
        return (LocalDateTime) get(5);
    }

    /**
     * Setter for <code>iq_specialization_doctor_mapping.updated_on</code>.
     */
    public IqSpecializationDoctorMappingRecord setUpdatedOn(LocalDateTime value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>iq_specialization_doctor_mapping.updated_on</code>.
     */
    public LocalDateTime getUpdatedOn() {
        return (LocalDateTime) get(6);
    }

    /**
     * Setter for <code>iq_specialization_doctor_mapping.updated_by</code>.
     */
    public IqSpecializationDoctorMappingRecord setUpdatedBy(Long value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for <code>iq_specialization_doctor_mapping.updated_by</code>.
     */
    public Long getUpdatedBy() {
        return (Long) get(7);
    }

    /**
     * Setter for <code>iq_specialization_doctor_mapping.client_id</code>.
     */
    public IqSpecializationDoctorMappingRecord setClientId(Integer value) {
        set(8, value);
        return this;
    }

    /**
     * Getter for <code>iq_specialization_doctor_mapping.client_id</code>.
     */
    public Integer getClientId() {
        return (Integer) get(8);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached IqSpecializationDoctorMappingRecord
     */
    public IqSpecializationDoctorMappingRecord() {
        super(IqSpecializationDoctorMapping.IQ_SPECIALIZATION_DOCTOR_MAPPING);
    }

    /**
     * Create a detached, initialised IqSpecializationDoctorMappingRecord
     */
    public IqSpecializationDoctorMappingRecord(Long id, Long doctorId, Long specializationId, String iqSpecializationcol, Long createdBy, LocalDateTime createdOn, LocalDateTime updatedOn, Long updatedBy, Integer clientId) {
        super(IqSpecializationDoctorMapping.IQ_SPECIALIZATION_DOCTOR_MAPPING);

        setId(id);
        setDoctorId(doctorId);
        setSpecializationId(specializationId);
        setIqSpecializationcol(iqSpecializationcol);
        setCreatedBy(createdBy);
        setCreatedOn(createdOn);
        setUpdatedOn(updatedOn);
        setUpdatedBy(updatedBy);
        setClientId(clientId);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised IqSpecializationDoctorMappingRecord
     */
    public IqSpecializationDoctorMappingRecord(com.assessment.assessment.database.tables.pojos.IqSpecializationDoctorMapping value) {
        super(IqSpecializationDoctorMapping.IQ_SPECIALIZATION_DOCTOR_MAPPING);

        if (value != null) {
            setId(value.getId());
            setDoctorId(value.getDoctorId());
            setSpecializationId(value.getSpecializationId());
            setIqSpecializationcol(value.getIqSpecializationcol());
            setCreatedBy(value.getCreatedBy());
            setCreatedOn(value.getCreatedOn());
            setUpdatedOn(value.getUpdatedOn());
            setUpdatedBy(value.getUpdatedBy());
            setClientId(value.getClientId());
            resetChangedOnNotNull();
        }
    }
}
