/*
 * This file is generated by jOOQ.
 */
package com.assessment.assessment.database.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class IqDoctor implements Serializable {

    private static final long serialVersionUID = 1L;

    private Long id;
    private Integer clientId;
    private String name;
    private Long specializationId;
    private Boolean isDeleted;
    private LocalDateTime createdOn;
    private Long createdBy;
    private LocalDateTime updatedOn;
    private Long updatedBy;

    public IqDoctor() {}

    public IqDoctor(IqDoctor value) {
        this.id = value.id;
        this.clientId = value.clientId;
        this.name = value.name;
        this.specializationId = value.specializationId;
        this.isDeleted = value.isDeleted;
        this.createdOn = value.createdOn;
        this.createdBy = value.createdBy;
        this.updatedOn = value.updatedOn;
        this.updatedBy = value.updatedBy;
    }

    public IqDoctor(
        Long id,
        Integer clientId,
        String name,
        Long specializationId,
        Boolean isDeleted,
        LocalDateTime createdOn,
        Long createdBy,
        LocalDateTime updatedOn,
        Long updatedBy
    ) {
        this.id = id;
        this.clientId = clientId;
        this.name = name;
        this.specializationId = specializationId;
        this.isDeleted = isDeleted;
        this.createdOn = createdOn;
        this.createdBy = createdBy;
        this.updatedOn = updatedOn;
        this.updatedBy = updatedBy;
    }

    /**
     * Getter for <code>iq_doctor.id</code>.
     */
    public Long getId() {
        return this.id;
    }

    /**
     * Setter for <code>iq_doctor.id</code>.
     */
    public IqDoctor setId(Long id) {
        this.id = id;
        return this;
    }

    /**
     * Getter for <code>iq_doctor.client_id</code>.
     */
    public Integer getClientId() {
        return this.clientId;
    }

    /**
     * Setter for <code>iq_doctor.client_id</code>.
     */
    public IqDoctor setClientId(Integer clientId) {
        this.clientId = clientId;
        return this;
    }

    /**
     * Getter for <code>iq_doctor.name</code>.
     */
    public String getName() {
        return this.name;
    }

    /**
     * Setter for <code>iq_doctor.name</code>.
     */
    public IqDoctor setName(String name) {
        this.name = name;
        return this;
    }

    /**
     * Getter for <code>iq_doctor.specialization_id</code>.
     */
    public Long getSpecializationId() {
        return this.specializationId;
    }

    /**
     * Setter for <code>iq_doctor.specialization_id</code>.
     */
    public IqDoctor setSpecializationId(Long specializationId) {
        this.specializationId = specializationId;
        return this;
    }

    /**
     * Getter for <code>iq_doctor.is_deleted</code>.
     */
    public Boolean getIsDeleted() {
        return this.isDeleted;
    }

    /**
     * Setter for <code>iq_doctor.is_deleted</code>.
     */
    public IqDoctor setIsDeleted(Boolean isDeleted) {
        this.isDeleted = isDeleted;
        return this;
    }

    /**
     * Getter for <code>iq_doctor.created_on</code>.
     */
    public LocalDateTime getCreatedOn() {
        return this.createdOn;
    }

    /**
     * Setter for <code>iq_doctor.created_on</code>.
     */
    public IqDoctor setCreatedOn(LocalDateTime createdOn) {
        this.createdOn = createdOn;
        return this;
    }

    /**
     * Getter for <code>iq_doctor.created_by</code>.
     */
    public Long getCreatedBy() {
        return this.createdBy;
    }

    /**
     * Setter for <code>iq_doctor.created_by</code>.
     */
    public IqDoctor setCreatedBy(Long createdBy) {
        this.createdBy = createdBy;
        return this;
    }

    /**
     * Getter for <code>iq_doctor.updated_on</code>.
     */
    public LocalDateTime getUpdatedOn() {
        return this.updatedOn;
    }

    /**
     * Setter for <code>iq_doctor.updated_on</code>.
     */
    public IqDoctor setUpdatedOn(LocalDateTime updatedOn) {
        this.updatedOn = updatedOn;
        return this;
    }

    /**
     * Getter for <code>iq_doctor.updated_by</code>.
     */
    public Long getUpdatedBy() {
        return this.updatedBy;
    }

    /**
     * Setter for <code>iq_doctor.updated_by</code>.
     */
    public IqDoctor setUpdatedBy(Long updatedBy) {
        this.updatedBy = updatedBy;
        return this;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final IqDoctor other = (IqDoctor) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.clientId == null) {
            if (other.clientId != null)
                return false;
        }
        else if (!this.clientId.equals(other.clientId))
            return false;
        if (this.name == null) {
            if (other.name != null)
                return false;
        }
        else if (!this.name.equals(other.name))
            return false;
        if (this.specializationId == null) {
            if (other.specializationId != null)
                return false;
        }
        else if (!this.specializationId.equals(other.specializationId))
            return false;
        if (this.isDeleted == null) {
            if (other.isDeleted != null)
                return false;
        }
        else if (!this.isDeleted.equals(other.isDeleted))
            return false;
        if (this.createdOn == null) {
            if (other.createdOn != null)
                return false;
        }
        else if (!this.createdOn.equals(other.createdOn))
            return false;
        if (this.createdBy == null) {
            if (other.createdBy != null)
                return false;
        }
        else if (!this.createdBy.equals(other.createdBy))
            return false;
        if (this.updatedOn == null) {
            if (other.updatedOn != null)
                return false;
        }
        else if (!this.updatedOn.equals(other.updatedOn))
            return false;
        if (this.updatedBy == null) {
            if (other.updatedBy != null)
                return false;
        }
        else if (!this.updatedBy.equals(other.updatedBy))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.clientId == null) ? 0 : this.clientId.hashCode());
        result = prime * result + ((this.name == null) ? 0 : this.name.hashCode());
        result = prime * result + ((this.specializationId == null) ? 0 : this.specializationId.hashCode());
        result = prime * result + ((this.isDeleted == null) ? 0 : this.isDeleted.hashCode());
        result = prime * result + ((this.createdOn == null) ? 0 : this.createdOn.hashCode());
        result = prime * result + ((this.createdBy == null) ? 0 : this.createdBy.hashCode());
        result = prime * result + ((this.updatedOn == null) ? 0 : this.updatedOn.hashCode());
        result = prime * result + ((this.updatedBy == null) ? 0 : this.updatedBy.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("IqDoctor (");

        sb.append(id);
        sb.append(", ").append(clientId);
        sb.append(", ").append(name);
        sb.append(", ").append(specializationId);
        sb.append(", ").append(isDeleted);
        sb.append(", ").append(createdOn);
        sb.append(", ").append(createdBy);
        sb.append(", ").append(updatedOn);
        sb.append(", ").append(updatedBy);

        sb.append(")");
        return sb.toString();
    }
}
