/*
 * This file is generated by jOOQ.
 */
package com.assessment.assessment.database.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class IqPatientDept implements Serializable {

    private static final long serialVersionUID = 1L;

    private Long id;
    private String name;
    private LocalDateTime dob;
    private String address;
    private Long doctorId;

    public IqPatientDept() {}

    public IqPatientDept(IqPatientDept value) {
        this.id = value.id;
        this.name = value.name;
        this.dob = value.dob;
        this.address = value.address;
        this.doctorId = value.doctorId;
    }

    public IqPatientDept(
        Long id,
        String name,
        LocalDateTime dob,
        String address,
        Long doctorId
    ) {
        this.id = id;
        this.name = name;
        this.dob = dob;
        this.address = address;
        this.doctorId = doctorId;
    }

    /**
     * Getter for <code>iq_patient_dept.id</code>.
     */
    public Long getId() {
        return this.id;
    }

    /**
     * Setter for <code>iq_patient_dept.id</code>.
     */
    public IqPatientDept setId(Long id) {
        this.id = id;
        return this;
    }

    /**
     * Getter for <code>iq_patient_dept.name</code>.
     */
    public String getName() {
        return this.name;
    }

    /**
     * Setter for <code>iq_patient_dept.name</code>.
     */
    public IqPatientDept setName(String name) {
        this.name = name;
        return this;
    }

    /**
     * Getter for <code>iq_patient_dept.dob</code>.
     */
    public LocalDateTime getDob() {
        return this.dob;
    }

    /**
     * Setter for <code>iq_patient_dept.dob</code>.
     */
    public IqPatientDept setDob(LocalDateTime dob) {
        this.dob = dob;
        return this;
    }

    /**
     * Getter for <code>iq_patient_dept.address</code>.
     */
    public String getAddress() {
        return this.address;
    }

    /**
     * Setter for <code>iq_patient_dept.address</code>.
     */
    public IqPatientDept setAddress(String address) {
        this.address = address;
        return this;
    }

    /**
     * Getter for <code>iq_patient_dept.doctor_id</code>.
     */
    public Long getDoctorId() {
        return this.doctorId;
    }

    /**
     * Setter for <code>iq_patient_dept.doctor_id</code>.
     */
    public IqPatientDept setDoctorId(Long doctorId) {
        this.doctorId = doctorId;
        return this;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final IqPatientDept other = (IqPatientDept) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.name == null) {
            if (other.name != null)
                return false;
        }
        else if (!this.name.equals(other.name))
            return false;
        if (this.dob == null) {
            if (other.dob != null)
                return false;
        }
        else if (!this.dob.equals(other.dob))
            return false;
        if (this.address == null) {
            if (other.address != null)
                return false;
        }
        else if (!this.address.equals(other.address))
            return false;
        if (this.doctorId == null) {
            if (other.doctorId != null)
                return false;
        }
        else if (!this.doctorId.equals(other.doctorId))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.name == null) ? 0 : this.name.hashCode());
        result = prime * result + ((this.dob == null) ? 0 : this.dob.hashCode());
        result = prime * result + ((this.address == null) ? 0 : this.address.hashCode());
        result = prime * result + ((this.doctorId == null) ? 0 : this.doctorId.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("IqPatientDept (");

        sb.append(id);
        sb.append(", ").append(name);
        sb.append(", ").append(dob);
        sb.append(", ").append(address);
        sb.append(", ").append(doctorId);

        sb.append(")");
        return sb.toString();
    }
}
