/*
 * This file is generated by jOOQ.
 */
package com.assessment.assessment.database.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class IqSpecializationMaster implements Serializable {

    private static final long serialVersionUID = 1L;

    private Long id;
    private String title;
    private String des;
    private Integer clientId;

    public IqSpecializationMaster() {}

    public IqSpecializationMaster(IqSpecializationMaster value) {
        this.id = value.id;
        this.title = value.title;
        this.des = value.des;
        this.clientId = value.clientId;
    }

    public IqSpecializationMaster(
        Long id,
        String title,
        String des,
        Integer clientId
    ) {
        this.id = id;
        this.title = title;
        this.des = des;
        this.clientId = clientId;
    }

    /**
     * Getter for <code>iq_specialization_master.id</code>.
     */
    public Long getId() {
        return this.id;
    }

    /**
     * Setter for <code>iq_specialization_master.id</code>.
     */
    public IqSpecializationMaster setId(Long id) {
        this.id = id;
        return this;
    }

    /**
     * Getter for <code>iq_specialization_master.title</code>.
     */
    public String getTitle() {
        return this.title;
    }

    /**
     * Setter for <code>iq_specialization_master.title</code>.
     */
    public IqSpecializationMaster setTitle(String title) {
        this.title = title;
        return this;
    }

    /**
     * Getter for <code>iq_specialization_master.des</code>.
     */
    public String getDes() {
        return this.des;
    }

    /**
     * Setter for <code>iq_specialization_master.des</code>.
     */
    public IqSpecializationMaster setDes(String des) {
        this.des = des;
        return this;
    }

    /**
     * Getter for <code>iq_specialization_master.client_id</code>.
     */
    public Integer getClientId() {
        return this.clientId;
    }

    /**
     * Setter for <code>iq_specialization_master.client_id</code>.
     */
    public IqSpecializationMaster setClientId(Integer clientId) {
        this.clientId = clientId;
        return this;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final IqSpecializationMaster other = (IqSpecializationMaster) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.title == null) {
            if (other.title != null)
                return false;
        }
        else if (!this.title.equals(other.title))
            return false;
        if (this.des == null) {
            if (other.des != null)
                return false;
        }
        else if (!this.des.equals(other.des))
            return false;
        if (this.clientId == null) {
            if (other.clientId != null)
                return false;
        }
        else if (!this.clientId.equals(other.clientId))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.title == null) ? 0 : this.title.hashCode());
        result = prime * result + ((this.des == null) ? 0 : this.des.hashCode());
        result = prime * result + ((this.clientId == null) ? 0 : this.clientId.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("IqSpecializationMaster (");

        sb.append(id);
        sb.append(", ").append(title);
        sb.append(", ").append(des);
        sb.append(", ").append(clientId);

        sb.append(")");
        return sb.toString();
    }
}
