/*
 * This file is generated by jOOQ.
 */
package com.assessment.assessment.database.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class IqSpecializationDoctorMapping implements Serializable {

    private static final long serialVersionUID = 1L;

    private Long id;
    private Long doctorId;
    private Long specializationId;
    private String iqSpecializationcol;
    private Long createdBy;
    private LocalDateTime createdOn;
    private LocalDateTime updatedOn;
    private Long updatedBy;
    private Integer clientId;

    public IqSpecializationDoctorMapping() {}

    public IqSpecializationDoctorMapping(IqSpecializationDoctorMapping value) {
        this.id = value.id;
        this.doctorId = value.doctorId;
        this.specializationId = value.specializationId;
        this.iqSpecializationcol = value.iqSpecializationcol;
        this.createdBy = value.createdBy;
        this.createdOn = value.createdOn;
        this.updatedOn = value.updatedOn;
        this.updatedBy = value.updatedBy;
        this.clientId = value.clientId;
    }

    public IqSpecializationDoctorMapping(
        Long id,
        Long doctorId,
        Long specializationId,
        String iqSpecializationcol,
        Long createdBy,
        LocalDateTime createdOn,
        LocalDateTime updatedOn,
        Long updatedBy,
        Integer clientId
    ) {
        this.id = id;
        this.doctorId = doctorId;
        this.specializationId = specializationId;
        this.iqSpecializationcol = iqSpecializationcol;
        this.createdBy = createdBy;
        this.createdOn = createdOn;
        this.updatedOn = updatedOn;
        this.updatedBy = updatedBy;
        this.clientId = clientId;
    }

    /**
     * Getter for <code>iq_specialization_doctor_mapping.id</code>.
     */
    public Long getId() {
        return this.id;
    }

    /**
     * Setter for <code>iq_specialization_doctor_mapping.id</code>.
     */
    public IqSpecializationDoctorMapping setId(Long id) {
        this.id = id;
        return this;
    }

    /**
     * Getter for <code>iq_specialization_doctor_mapping.doctor_id</code>.
     */
    public Long getDoctorId() {
        return this.doctorId;
    }

    /**
     * Setter for <code>iq_specialization_doctor_mapping.doctor_id</code>.
     */
    public IqSpecializationDoctorMapping setDoctorId(Long doctorId) {
        this.doctorId = doctorId;
        return this;
    }

    /**
     * Getter for
     * <code>iq_specialization_doctor_mapping.specialization_id</code>.
     */
    public Long getSpecializationId() {
        return this.specializationId;
    }

    /**
     * Setter for
     * <code>iq_specialization_doctor_mapping.specialization_id</code>.
     */
    public IqSpecializationDoctorMapping setSpecializationId(Long specializationId) {
        this.specializationId = specializationId;
        return this;
    }

    /**
     * Getter for
     * <code>iq_specialization_doctor_mapping.iq_specializationcol</code>.
     */
    public String getIqSpecializationcol() {
        return this.iqSpecializationcol;
    }

    /**
     * Setter for
     * <code>iq_specialization_doctor_mapping.iq_specializationcol</code>.
     */
    public IqSpecializationDoctorMapping setIqSpecializationcol(String iqSpecializationcol) {
        this.iqSpecializationcol = iqSpecializationcol;
        return this;
    }

    /**
     * Getter for <code>iq_specialization_doctor_mapping.created_by</code>.
     */
    public Long getCreatedBy() {
        return this.createdBy;
    }

    /**
     * Setter for <code>iq_specialization_doctor_mapping.created_by</code>.
     */
    public IqSpecializationDoctorMapping setCreatedBy(Long createdBy) {
        this.createdBy = createdBy;
        return this;
    }

    /**
     * Getter for <code>iq_specialization_doctor_mapping.created_on</code>.
     */
    public LocalDateTime getCreatedOn() {
        return this.createdOn;
    }

    /**
     * Setter for <code>iq_specialization_doctor_mapping.created_on</code>.
     */
    public IqSpecializationDoctorMapping setCreatedOn(LocalDateTime createdOn) {
        this.createdOn = createdOn;
        return this;
    }

    /**
     * Getter for <code>iq_specialization_doctor_mapping.updated_on</code>.
     */
    public LocalDateTime getUpdatedOn() {
        return this.updatedOn;
    }

    /**
     * Setter for <code>iq_specialization_doctor_mapping.updated_on</code>.
     */
    public IqSpecializationDoctorMapping setUpdatedOn(LocalDateTime updatedOn) {
        this.updatedOn = updatedOn;
        return this;
    }

    /**
     * Getter for <code>iq_specialization_doctor_mapping.updated_by</code>.
     */
    public Long getUpdatedBy() {
        return this.updatedBy;
    }

    /**
     * Setter for <code>iq_specialization_doctor_mapping.updated_by</code>.
     */
    public IqSpecializationDoctorMapping setUpdatedBy(Long updatedBy) {
        this.updatedBy = updatedBy;
        return this;
    }

    /**
     * Getter for <code>iq_specialization_doctor_mapping.client_id</code>.
     */
    public Integer getClientId() {
        return this.clientId;
    }

    /**
     * Setter for <code>iq_specialization_doctor_mapping.client_id</code>.
     */
    public IqSpecializationDoctorMapping setClientId(Integer clientId) {
        this.clientId = clientId;
        return this;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final IqSpecializationDoctorMapping other = (IqSpecializationDoctorMapping) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.doctorId == null) {
            if (other.doctorId != null)
                return false;
        }
        else if (!this.doctorId.equals(other.doctorId))
            return false;
        if (this.specializationId == null) {
            if (other.specializationId != null)
                return false;
        }
        else if (!this.specializationId.equals(other.specializationId))
            return false;
        if (this.iqSpecializationcol == null) {
            if (other.iqSpecializationcol != null)
                return false;
        }
        else if (!this.iqSpecializationcol.equals(other.iqSpecializationcol))
            return false;
        if (this.createdBy == null) {
            if (other.createdBy != null)
                return false;
        }
        else if (!this.createdBy.equals(other.createdBy))
            return false;
        if (this.createdOn == null) {
            if (other.createdOn != null)
                return false;
        }
        else if (!this.createdOn.equals(other.createdOn))
            return false;
        if (this.updatedOn == null) {
            if (other.updatedOn != null)
                return false;
        }
        else if (!this.updatedOn.equals(other.updatedOn))
            return false;
        if (this.updatedBy == null) {
            if (other.updatedBy != null)
                return false;
        }
        else if (!this.updatedBy.equals(other.updatedBy))
            return false;
        if (this.clientId == null) {
            if (other.clientId != null)
                return false;
        }
        else if (!this.clientId.equals(other.clientId))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.doctorId == null) ? 0 : this.doctorId.hashCode());
        result = prime * result + ((this.specializationId == null) ? 0 : this.specializationId.hashCode());
        result = prime * result + ((this.iqSpecializationcol == null) ? 0 : this.iqSpecializationcol.hashCode());
        result = prime * result + ((this.createdBy == null) ? 0 : this.createdBy.hashCode());
        result = prime * result + ((this.createdOn == null) ? 0 : this.createdOn.hashCode());
        result = prime * result + ((this.updatedOn == null) ? 0 : this.updatedOn.hashCode());
        result = prime * result + ((this.updatedBy == null) ? 0 : this.updatedBy.hashCode());
        result = prime * result + ((this.clientId == null) ? 0 : this.clientId.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("IqSpecializationDoctorMapping (");

        sb.append(id);
        sb.append(", ").append(doctorId);
        sb.append(", ").append(specializationId);
        sb.append(", ").append(iqSpecializationcol);
        sb.append(", ").append(createdBy);
        sb.append(", ").append(createdOn);
        sb.append(", ").append(updatedOn);
        sb.append(", ").append(updatedBy);
        sb.append(", ").append(clientId);

        sb.append(")");
        return sb.toString();
    }
}
