/*
 * This file is generated by jOOQ.
 */
package com.assessment.assessment.database;


import com.assessment.assessment.database.tables.IqDoctor;
import com.assessment.assessment.database.tables.IqPatientDept;
import com.assessment.assessment.database.tables.IqSpecializationDoctorMapping;
import com.assessment.assessment.database.tables.IqSpecializationMaster;
import com.assessment.assessment.database.tables.IqSurgeryDept;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DefaultSchema extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>DEFAULT_SCHEMA</code>
     */
    public static final DefaultSchema DEFAULT_SCHEMA = new DefaultSchema();

    /**
     * The table <code>iq_doctor</code>.
     */
    public final IqDoctor IQ_DOCTOR = IqDoctor.IQ_DOCTOR;

    /**
     * The table <code>iq_patient_dept</code>.
     */
    public final IqPatientDept IQ_PATIENT_DEPT = IqPatientDept.IQ_PATIENT_DEPT;

    /**
     * The table <code>iq_specialization_doctor_mapping</code>.
     */
    public final IqSpecializationDoctorMapping IQ_SPECIALIZATION_DOCTOR_MAPPING = IqSpecializationDoctorMapping.IQ_SPECIALIZATION_DOCTOR_MAPPING;

    /**
     * The table <code>iq_specialization_master</code>.
     */
    public final IqSpecializationMaster IQ_SPECIALIZATION_MASTER = IqSpecializationMaster.IQ_SPECIALIZATION_MASTER;

    /**
     * The table <code>iq_surgery_dept</code>.
     */
    public final IqSurgeryDept IQ_SURGERY_DEPT = IqSurgeryDept.IQ_SURGERY_DEPT;

    /**
     * No further instances allowed
     */
    private DefaultSchema() {
        super("", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            IqDoctor.IQ_DOCTOR,
            IqPatientDept.IQ_PATIENT_DEPT,
            IqSpecializationDoctorMapping.IQ_SPECIALIZATION_DOCTOR_MAPPING,
            IqSpecializationMaster.IQ_SPECIALIZATION_MASTER,
            IqSurgeryDept.IQ_SURGERY_DEPT
        );
    }
}
