/*
 * This file is generated by jOOQ.
 */
package com.assessment.assessment.database;


import com.assessment.assessment.database.tables.IqDoctor;
import com.assessment.assessment.database.tables.IqPatientDept;
import com.assessment.assessment.database.tables.IqSpecializationDoctorMapping;
import com.assessment.assessment.database.tables.IqSpecializationMaster;
import com.assessment.assessment.database.tables.IqSurgeryDept;
import com.assessment.assessment.database.tables.records.IqDoctorRecord;
import com.assessment.assessment.database.tables.records.IqPatientDeptRecord;
import com.assessment.assessment.database.tables.records.IqSpecializationDoctorMappingRecord;
import com.assessment.assessment.database.tables.records.IqSpecializationMasterRecord;
import com.assessment.assessment.database.tables.records.IqSurgeryDeptRecord;

import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables in the
 * default schema.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<IqDoctorRecord> KEY_IQ_DOCTOR_PRIMARY = Internal.createUniqueKey(IqDoctor.IQ_DOCTOR, DSL.name("KEY_iq_doctor_PRIMARY"), new TableField[] { IqDoctor.IQ_DOCTOR.ID }, true);
    public static final UniqueKey<IqPatientDeptRecord> KEY_IQ_PATIENT_DEPT_PRIMARY = Internal.createUniqueKey(IqPatientDept.IQ_PATIENT_DEPT, DSL.name("KEY_iq_patient_dept_PRIMARY"), new TableField[] { IqPatientDept.IQ_PATIENT_DEPT.ID }, true);
    public static final UniqueKey<IqSpecializationDoctorMappingRecord> KEY_IQ_SPECIALIZATION_DOCTOR_MAPPING_PRIMARY = Internal.createUniqueKey(IqSpecializationDoctorMapping.IQ_SPECIALIZATION_DOCTOR_MAPPING, DSL.name("KEY_iq_specialization_doctor_mapping_PRIMARY"), new TableField[] { IqSpecializationDoctorMapping.IQ_SPECIALIZATION_DOCTOR_MAPPING.ID }, true);
    public static final UniqueKey<IqSpecializationMasterRecord> KEY_IQ_SPECIALIZATION_MASTER_PRIMARY = Internal.createUniqueKey(IqSpecializationMaster.IQ_SPECIALIZATION_MASTER, DSL.name("KEY_iq_specialization_master_PRIMARY"), new TableField[] { IqSpecializationMaster.IQ_SPECIALIZATION_MASTER.ID }, true);
    public static final UniqueKey<IqSurgeryDeptRecord> KEY_IQ_SURGERY_DEPT_PRIMARY = Internal.createUniqueKey(IqSurgeryDept.IQ_SURGERY_DEPT, DSL.name("KEY_iq_surgery_dept_PRIMARY"), new TableField[] { IqSurgeryDept.IQ_SURGERY_DEPT.ID }, true);
}
