/*
 * This file is generated by jOOQ.
 */
package com.assessment.assessment.database;


import com.assessment.assessment.database.tables.IqDoctor;
import com.assessment.assessment.database.tables.IqPatientDept;
import com.assessment.assessment.database.tables.IqSpecializationDoctorMapping;
import com.assessment.assessment.database.tables.IqSpecializationMaster;
import com.assessment.assessment.database.tables.IqSurgeryDept;


/**
 * Convenience access to all tables in the default schema.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>iq_doctor</code>.
     */
    public static final IqDoctor IQ_DOCTOR = IqDoctor.IQ_DOCTOR;

    /**
     * The table <code>iq_patient_dept</code>.
     */
    public static final IqPatientDept IQ_PATIENT_DEPT = IqPatientDept.IQ_PATIENT_DEPT;

    /**
     * The table <code>iq_specialization_doctor_mapping</code>.
     */
    public static final IqSpecializationDoctorMapping IQ_SPECIALIZATION_DOCTOR_MAPPING = IqSpecializationDoctorMapping.IQ_SPECIALIZATION_DOCTOR_MAPPING;

    /**
     * The table <code>iq_specialization_master</code>.
     */
    public static final IqSpecializationMaster IQ_SPECIALIZATION_MASTER = IqSpecializationMaster.IQ_SPECIALIZATION_MASTER;

    /**
     * The table <code>iq_surgery_dept</code>.
     */
    public static final IqSurgeryDept IQ_SURGERY_DEPT = IqSurgeryDept.IQ_SURGERY_DEPT;
}
